### ISSUE TITLE
Request for Comment : Add Introduction to Abstract Algebra (Group Theory) under Core Mathematics

### ISSUE THREAD

**Issue by aayushsinha0706** [ossu/math#15]
**Problem:**
OSSU Math does not introduce abstract algebra in its core curriculum

**Duration:**
January 07, 2022.

**Background:**
OSSU promises the equivalent of education an undergraduate education in Mathematics. In order to evaluate our recommended courses, we use the [CUPM 2015 guideline](https://www.maa.org/node/790342) that specifies number of mathematical areas a student should cover.

Let us visit [Abstract Algebra ](https://www.maa.org/sites/default/files/abstractalgebra.pdf) section of CUPM 2015. 

What CUPM 2015 says about Algebra A (Intro to Abstract Algebra)
>This course offers what we feel is a standard model for a first-semester Abstract Algebra course suitable for nearly every college or university. We feel some tension between the breadth of a first course that includes both groups and rings and the depth of one that focuses only on groups or only on rings. One argument for breadth is that both rings and groups are implicit in the pre-collegiate curriculum, and we feel that every student would benefit from an opportunity to see these concepts developed. For example, pre-college students encounter the rings of integers, rational numbers, real numbers, polynomials etc. and they will probably have also seen various groups of symmetries, both in the elementary grades and in high school geometry. We thus recommend that this one-semester course should cover both groups and rings, and also (lightly) fields. **A disadvantage of this breadth is, of course, that the student has less opportunity to explore a single structure in depth. For this reason, some institutions might wish to offer an alternative first Abstract Algebra course that focuses more deeply one area: for example finite group theory.** Such a course might start with definitions and examples, and eventually reach a proof of the Sylow existence theorem, and perhaps more.

>The order of the topics can be chosen to suit the instructor’s preference. Whichever of groups or rings is studied first, the student has the experience of learning one structure and then seeing the parallels in the second. (The analogy we make is to learning a computer language, and then the empowerment that comes with the realization of how much easier it is to learn a second language.) Our study group prefer groups first, because of their simpler definition (only one binary operation and fewer axioms) and because the familiarity of the integers and the real numbers can hide from students which statements require proof. On the other hand, we recognize that some instructors prefer to begin with rings exactly because of their familiarity to students. Studying rings first also provides some useful facts about the integers such as the division algorithm and properties of the greatest common divisor.

Topics covered under the suggestion 

**Groups**

- Definitions and examples of groups and subgroups.
- Cyclic groups and their subgroups, and the orders of elements.
- Symmetric groups, cycle notation, parity of a permutation and the alternating group.
- Isomorphisms and Cayley’s Theorem. (See the remarks below.
- Cosets and Lagrange’s Theorem, the falsity of the converse of Lagrange’s Theorem, and if time permits, the statement of the Sylow existence theorem.
- Group actions. (See the remarks below.)
- External direct products, if time permits.
- Normal subgroups and factor groups, conjugates of a subgroup and of an element.
- Homomorphisms, and the Fundamental Homomorphism Theorem

**Rings**
- Definitions and examples of rings and fields.
-  Ideals and factor rings.
- Principal ideals, integral domains, principal ideal domains, maximal and prime ideals.
- Homomorphisms, the Fundamental Homomorphism Theorem, the theorem that a com- mutative ring modulo a maximal ideal is a field.
- Polynomial rings and irreducible polynomials.

**Topics covered by course**
- Motivation, definition, examples and basic properties 
- Subgroups, subgroups of integers, homomorphisms 
- Quotient groups, isomorphism theorems
- Group operations, counting formula
- Symmetric groups
- Operations of a group on itself, class equation 
- Sylow theorems I
- Sylow theorems II

The course does not cover rings as an introduction but goes well around in depth covering groups.

As mentioned CUPM 2015 Abstract Algebra guideline
> A disadvantage of this breadth is, of course, that the student has less opportunity to explore a single structure in depth. For this reason, some institutions might wish to offer an alternative first Abstract Algebra course that focuses more deeply one area: for example finite group theory.

**Proposal:**
Add these course to core Math curriculum as **Introduction to Abstract Algebra(Group Theory)** 
- [Introduction to Abstract Algebra(Group Theory)](https://nptel.ac.in/courses/111/106/111106113/)

The course also has its [syllabus](https://nptel.ac.in/content/syllabus_pdf/111106113.pdf) page that specifies pre-requisites of the course, introduction to instructor and topic that will be covered.

Pre-Requisite for the course that is mentioned is high school mathematics although I recommend Linear Algebra to be its co-requisite. 

The course has also its own book and set of assignments that can be accessed via course site.

This course will take duration of 8 weeks with effort of 6-7hours/week to complete.

**Comment by riyan-ahmed** [comment]
I agree, groups,rings,and fields are all strong prerequisites for advanced topics. Abstract algebra should be in the core curriculum.

**Comment by aayushsinha0706** [comment]
> I agree, groups,rings,and fields are all strong prerequisites for advanced topics. Abstract algebra should be in the core curriculum.

Yes, I agree atleast a basic abstract algebra should be in core curriculum. Students in UK study group theory in their first year. It should be in core curriculum.

**Comment by r0hitm** [comment]
Sounds interesting, what will be prerequisites for taking this course? or anyone who has done high-school math will be able to do it.

**Comment by uRSTEnzY** [comment]
Multivariable calculus and Linear Algebra would be the bare minimum prerequisites.  I would argue a solid proof writing background is required as well.  On the plus side, you can get this background from a rigorous calculus sequence to avoid taking an extra course.

**Comment by bradleygrant** [comment]
@aayushsinha0706 

Looks like a decent suggestion to me. I recommend you fork the project, make the change you'd like to make and submit a PR for review.

**Comment by waciumawanjohi** [comment]
This is a well supported case for inclusion of the topic.

In terms of the course offering itself, I could find no better alternative with a quick search. Indeed, I found [an old /r/math thread](https://www.reddit.com/r/math/comments/4ss1jb/mooc_on_abstract_algebra_starting_july_18/) recommending a former NPTEL course on abstract algebra and the commenters in the thread had been unable to find better resources.

I would approve this PR.

**Comment by aayushsinha0706** [comment]
Today morning I found sequel to the course that can solve the issue of breadth vs depth of the topic in this RFC

[Introduction to Rings and Fields](https://nptel.ac.in/courses/111/106/111106131/)
The course is by the same instructor.

Upon reviewing this course I found the topics recommended and topics covered by course are at most same.

Suggestion by CUPM 2015

**Rings**
- Definitions and examples of rings and fields.
-  Ideals and factor rings.
- Principal ideals, integral domains, principal ideal domains, maximal and prime ideals.
- Homomorphisms, the Fundamental Homomorphism Theorem, the theorem that a com- mutative ring modulo a maximal ideal is a field.
- Polynomial rings and irreducible polynomials.

Topics Covered by this course
- Week 1: Definition of rings, examples, polynomial rings, homomorphisms. 
- Week 2: Ideals, prime and maximal ideals, quotient rings.
- Week 3: Noetherian rings, Hilbert basis theorem.
- Week 4: Integral domains, quotient fields.
- Week 5: Unique factorization domains, principal ideal domains.
- Week 6: Definition of fields, examples, degree of field extensions.
- Week 7: Adjoining roots, primitive element theorem.
- Week 8: Finite fields.

The course has its [syllabus](https://nptel.ac.in/content/syllabus_pdf/111106131.pdf) page that says Intro to abstract group theory is its pre-requisite. Both courses together will definitely reflect what Algebra A says or maybe even better.

The course will take 8 weeks of effort with an effort of 6-7hours/week.

**Proposal**

Add both these courses as 

**Introduction to Abstract Algebra**
- [Introduction to Abstract Algebra(Group Theory)](https://nptel.ac.in/courses/111/106/111106113/)
- [Introduction to Rings and Fields](https://nptel.ac.in/courses/111/106/111106131/)

**Comment by spamegg1** [comment]
Great work @aayushsinha0706 

These two courses together cover all of "Algebra A", and most of "Algebra B" except Linear Algebra and Module Theory. But that's fine. Linear Algebra has its own course in the curriculum, and Module Theory will be missing, an acceptable compromise.

We don't have to worry too much about the "breadth vs. depth" issue, since we don't have to squeeze everything into one semester like a real university. These two courses are a great fit for Core.

Please make a pull request!

**Comment by spamegg1** [comment]
Thanks to everyone and @aayushsinha0706 , closing the issue.
