### ISSUE TITLE
Request to add optional courses for Calculus

### ISSUE THREAD

**Issue by rohitdavas** [ossu/math#16]
Hi, 

The courses offered through edx are instructor timed. That makes it difficult to start. Calculus 1A was already started and ends on sept 2.  I will need to wait for it's offering again. Since it's a series, i can't take other courses in series before taking the prerequisite course 1A ( even though i can, i should not without the prerequisites to completely understand the course ) 

Is there a possibility to give equivalent course here which are self-paced ?

**Comment by aayushsinha0706** [comment]
You can take same courses by MIT in OpenLibrary by MIT itself. Only downside you won't get the certificate here 

[18.01.1x
Calculus 1A: Differentiation](https://openlearninglibrary.mit.edu/courses/course-v1:MITx+18.01.1x+2T2019/about)

[18.01.2x
Calculus 1B: Integration](https://openlearninglibrary.mit.edu/courses/course-v1:MITx+18.01.2x+3T2019/about)

[18.01.3x
Calculus 1C: Coordinate Systems & Infinite Series](https://openlearninglibrary.mit.edu/courses/course-v1:MITx+18.01.3x+1T2020/about)

**Comment by rohitdavas** [comment]
Thankyou
