### ISSUE TITLE
Calculus 1A: Differentiation is no longer available at eDx

### ISSUE THREAD

**Issue by tyashin** [ossu/math#17]
Calculus 1A: Differentiation is no longer available at eDx.
Please, provide equivalent alternative  for this course.

As far as I understand, copy of this course is available for free here: https://openlearninglibrary.mit.edu/courses/course-v1:MITx+18.01.1x+2T2019/course/ although, **there's no way to get a certificate**.

**Comment by tyashin** [comment]
As far as I understand, copy of this course is available for free here: https://openlearninglibrary.mit.edu/courses/course-v1:MITx+18.01.1x+2T2019/course/ although, there's no way to get a certificate.

**Comment by spamegg1** [comment]
As of Dec 08, 2021 the course is available on edX, as an "archived course". It says it "ended on Sep 1, 2021". The only unavailable part is the Final Exam. I just "viewed archived course" and did this today:
![today](https://user-images.githubusercontent.com/4255997/145257685-3f1dbd7c-fdbc-49a5-ab4c-db9487cf9fb9.png)

There are multiple versions of the same courses on edX, this might be the source of confusion. There are courses accessed with "View course" and with "View archived course":
![arch](https://user-images.githubusercontent.com/4255997/145258375-cb793ba9-23a6-411a-ba9f-929bcec94790.png)

@tyashin Maybe your access expired? This is a common issue on edX as they have a short time limit for free use. Or the course itself was on a schedule and it ended? This is what it currently says on Calculus 1B:
![calc1B](https://user-images.githubusercontent.com/4255997/145257887-c371af45-377e-4470-89d0-94b137a00516.png)

Also possible is that edX themselves are going through some big changes, so they are probably moving things around a lot. They recently switched from non-profit to profit:
![edxLOL](https://user-images.githubusercontent.com/4255997/145258853-d1118f33-aa49-40d0-b211-aaf019604e17.png)


The OLL versions are missing the Homeworks from the edX versions (the "Homework Part A/B" labeled parts at the end of each Unit), which have a lot of questions. I have solved every single one of those questions and they are very important:

This is OLL:
![OLL](https://user-images.githubusercontent.com/4255997/145258543-b12c2e58-c302-427c-a819-751b58359fe5.png)

This is the edX version:
![edxver](https://user-images.githubusercontent.com/4255997/145258725-125c4600-e381-4901-b766-30d88c286c6b.png)

I can add the OLL versions as alternative backups.

**Comment by tyashin** [comment]
Thank you, @spamegg1. At this point I'm OK with the lack of certificates. Both links for this course work (at eDx and at MIT.edu)

**Comment by spamegg1** [comment]
@tyashin Great, thanks for the confirmation.
