### ISSUE TITLE
Links Under Curriculum Should Lead to Sections Not Direct Courses

### ISSUE THREAD

**Issue by uRSTEnzY** [ossu/math#2]
When clicking a link under the [Curriculum Section](https://github.com/ossu/math/blob/master/README.md#curriculum), the user is taken to a specific course.  Links should be updated to take user to that section.

Current Behavior:  Clicking Introduction to Mathematical Thinking takes users directly to the Coursera course.
Desired Behavior:  Clicking Introduction to Mathematical Thinking takes users to the [Introduction to Mathematical Thinking section](https://github.com/ossu/math/blob/master/README.md#introductory-mathematics).

**Comment by waciumawanjohi** [comment]
Closing as complete, the desired behavior has been implemented.
