### ISSUE TITLE
RFC : Addition of Probability and Statistics courses in Advanced Math

### ISSUE THREAD

**Issue by aayushsinha0706** [ossu/math#24]
**Problem:**
Addition of Prbobaility and Statistics courses in its Advanced Maths

**Duration:**
March 19, 2022.

**Background:**
OSSU promises the equivalent of education an undergraduate education in Mathematics. To evaluate our recommended courses, we use the [CUPM 2015 guideline](https://www.maa.org/node/790342) that specifies the number of mathematical areas a student should cover.

We will be referring to two docs here [Probability and Stochastic Process](https://www.maa.org/sites/default/files/Probability.pdf)  and  [Applied Statistics and Data Analysis](https://www.maa.org/sites/default/files/AppliedStatDataAnalysis.pdf)

**Introducing Second Probability Course : Stochastic Process**

What CUPM 2015 says

>A second undergraduate probability course, if offered at all, is usually about stochastic processes. Stochastic processes are important in operations research, applied mathematics, computer science, actuarial science, engineering, and financial mathematics. Either version of the probability course can be a prerequisite, although obviously the stochastic process-oriented version is better.

> In this course, students should formulate models, gain analytical skills, perform and analyze simulations, and present results to others. They should be encouraged to use computational tools where appropriate and to follow more involved proofs than in the prior (required) probability course. For more about a stochastic operations research course, see the Operations Research Program Area report.

To learn Stochastic Processes I recommend this course
[Stochastic Processes](https://www.coursera.org/learn/stochasticprocesses)

Few reviews of this course is here
[Reviews](https://gist.github.com/aayushsinha0706/01cd1293c623742b7ab5dcc929f66cdd)

Now lets come to a statistics course. OSSU does not lack a statistics course but does lack a data analysis course.

What CUPM 2015 says

>For students majoring in the mathematical sciences, we recommend a course focused on applied data analysis and driven by real data. The course should stress conceptual understanding, foster active learning, and introduce students to statistical technology. The focus should be on the effective collection and analysis of data, along with appropriate interpretation and communication of results.

>Just as Mathematics Departments routinely do with calculus courses, such a course in Applied Statistics can serve a wide audience. Also as with calculus, some institutions will have one level of the course while other larger institutions might have different courses for different audiences. In every case, however, the focus should be on understanding effective data analysis rather than on the underlying mathematical theory

One course they recommend is Applied Statistics focusing on Data Analysis

Course Outline:
● Data collection, including random sampling and design of experiments (2 weeks)
● Data description, including graphs and summary statistics for categorical and quantitative
variables and relationships between variables (2 weeks)
● Introduction to the key ideas of estimation and testing, using modern resampling methods to
build conceptual understanding (3 weeks)
● More on confidence intervals and hypothesis tests, using the normal and t distributions (3
weeks)
● Advanced tests, as time permits, such as chi-square tests, ANOVA, regression tests, multiple
regression (3 weeks)

I recommend this course to study Data Analysis
[Data Analysis](https://nptel.ac.in/courses/111/104/111104147)

The course covers
Week 1: Introduction to data science and Calculations with R Software
Week 2: Basic Fundamentals of Sampling
Week 3: Simple Random Sampling
Week 4: Simple Random Sampling with R
Week 5: Stratified Random Sampling
Week 6: Stratified Random Sampling with R
Week 7: Bootstrap Methodology with R
Week 8: Introduction to Linear Models and Regression and Simple linear regression Analysis 
Week 9: Simple Linear Regression Analysis with R
Week 10: Multiple Linear Regression Analysis
Week 11: Multiple Linear Regression Analysis with R
Week 12: Variable Selection using LASSO Regression

Only drawback of the course you need to know R Programming for which I will recommend this course by same instructor 
[R Programming](https://nptel.ac.in/courses/111/104/111104100/)

Following two courses will cover the knowledge of Game Theory which will also be an pre-requisite for Combinatorial Math course that i am going to recommend in future

[Game Theory](https://www.coursera.org/learn/game-theory-1)
[Game Theory II](https://www.coursera.org/learn/game-theory-2)

Proposal

Add the above courses as following

## Probability and Statistics

Courses | Duration | Effort | Prerequisites
:-- | :--: | :--: | :--:
[Discrete Stochastic Process](https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-262-discrete-stochastic-processes-spring-2011/index.htm) | 12 weeks | 5-6 hours/week | Probability 
[Statistical Learning](https://www.edx.org/course/statistical-learning) | 12 weeks | 4-5 hours/week | [Beginning Computer Science with R](https://homerhanumat.github.io/r-notes/index.html), Probability and Applied Statistics
[Game Theory](https://www.coursera.org/learn/game-theory-1) | 8 weeks | 4-5 hours/week | Probability and Calculus 1C
[Game Theory II](https://www.coursera.org/learn/game-theory-2) | 5 weeks | 5-6 hours/week |Game Theory

**Alternatives**

[Stochastic processes](https://nptel.ac.in/courses/111102098) 

[Data Analysis](https://nptel.ac.in/courses/111104147) and [R Programming](https://nptel.ac.in/courses/111104100)

**Comment by waciumawanjohi** [comment]
The stochastic process course is no longer offered on Coursera. I would guess that it is a course from a Russian university, as Coursera recently removed all such courses from their platform.

**Comment by waciumawanjohi** [comment]
The Data Analysis course link appears to be broken and links to a page with the message:
> You may come across some features or links in our new NPTEL site not fully functional. We are doing our best to resolve all the issues as quickly as possible. Please provide your suggestions/feedback at this link: [click here](https://docs.google.com/forms/d/e/1FAIpQLSd8zS-9aal7K220DawDa6uneSkKUrzGszmMt6QrbQHrOmmdfg/viewform)
If you are facing any difficulties with the new site, and want to access our old site, please go to https://archive.nptel.ac.in/

**Comment by waciumawanjohi** [comment]
I would not say that this RFC has provided adequate justification for the inclusion of the Game Theory courses. Perhaps that justification should come in the promised Combinatorial Math proposal? Or more information on why these courses should be added today in the comments?

**Comment by aayushsinha0706** [comment]
> Fixed Data Analysis class with R programming links as NPTEL have updated their whole program

[Data Analysis](https://nptel.ac.in/courses/111104147) and [R Programming](https://nptel.ac.in/courses/111104100) 

> Regarding Stochastic Processes class which was offered by Coursera at the time when this RFC was released.

We have two choice of courses here 

A more mathematical oriented course [Stochastic processes](https://nptel.ac.in/courses/111102098) 
>This course explanations and expositions of stochastic processes concepts which they need for their experiments and research. It also covers theoretical concepts pertaining to handling various stochastic modeling. This course provides classification and properties of stochastic processes, discrete and continuous time Markov chains, simple Markovian queueing models, applications of CTMC, martingales, Brownian motion, renewal processes, branching processes, stationary and autoregressive processes.

or 

An applied math course oriented towards Comp Sci [Discrete Stochastic Processes](https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-262-discrete-stochastic-processes-spring-2011/index.htm)
>Discrete stochastic processes are essentially probabilistic systems that evolve in time via random changes occurring at discrete fixed or random intervals. This course aims to help students acquire both the mathematical principles and the intuition necessary to create, analyze, and understand insightful models for a broad range of these processes. The range of areas for which discrete stochastic-process models are useful is constantly expanding, and includes many applications in engineering, physics, biology, operations research and finance.

**Comment by aayushsinha0706** [comment]
Mentioned about Game Theory in RFC #27 that Game Theory 1 is a pre-requisite to Analysis of Algorithms.

While Game Theory 2 may be added for students who would like to have more advanced studies in topic of Game Theory

**Comment by aayushsinha0706** [comment]
**UPDATE : 10 MARCH 2022**

[Statistical Learning](https://www.edx.org/course/statistical-learning)

A very interesting course was brought into light by @bradleygrant in the data science discord. Upon looking the course and textbook it seemed to be very interesting and is a great material to be added as an Data Analysis course. The course is offered by Stanford  and has really good reviews that can replace IIT Madras course on Data Analysis.

The course pre-requisites are first courses in statistics, linear algebra, and computing. We can offer this text as first computing course in R [Beginning Computer Science with R](https://homerhanumat.github.io/r-notes/index.html)

Moved Data Analysis and R programming by IIT Madras to alternatives.

**Comment by aayushsinha0706** [comment]
Closing down this issue and new issue will be made in near future for courses in Probability, Statistics and Combinatorial math.
