### ISSUE TITLE
Lets add a LaTeX course

### ISSUE THREAD

**Issue by angle943** [ossu/math#29]
Sort of like how we have "The missing semester of Your CS Education" under CS, we should consider having a LaTeX course in this track. I'm not sure of any good latex courses though

**Comment by waciumawanjohi** [comment]
> we should consider having a LaTeX course in this track

Can you add some justification to this statement? I will say, I'm skeptical that this will benefit most students.

**Comment by angle943** [comment]
@waciumawanjohi The justification would be the same justification as to why "The Missing Semester of Your CS Education" is on the OSSU Comp Sci track.

Learning about Terminals, shell scripting, version control, etc are not typically taught in universities, but:

1) Many classes assume you know it already, or gives you such a bare bones intro on it that it often times leaves you unsatisfied
2) After graduating, this knowledge is crucial as you want to progress to a career in programming.

For the above two reasons, I believe that having "The Missing Semester of your CS Education" is warranted in the CS track. And likewise, since LaTeX is essentially required to write any meaningful math on the computer in undergraduate or greater type mathematics, I think it would be a good fit to have on the math course.

Perhaps it can be under a section called "Math Tools" (like how CS track has "CS Tools"), and as an aside, it might even be useful to have a mathematica/matlab/python(?) course there (i'm not sure what the popular math programming tool is these days)

**Comment by waciumawanjohi** [comment]
These seem like possible Latex course options:

- https://www.edx.org/course/latex-for-students-engineers-and-scientists-2
- https://latex-tutorial.com/tutorials/
- https://en.wikibooks.org/wiki/LaTeX
- https://www.resurchify.com/latex_tutorial/latex_tutorial.php

Including one of these in a math tools section would entail evaluating the course. I recommend looking at a few issues that successfully added courses to the math or CS curriculum. These can be examples of the type of evidence/discussion that can demonstrate a course's suitability.

In exploring other tools that could be appropriate for addition, [our curricular guideline](https://github.com/ossu/math/blob/master/CURRICULAR_GUIDELINES.md) includes a "Technology and the Mathematics Curriculum" section that would be useful to review and reference.

**Comment by angle943** [comment]
I will try looking at some of those and see which ones will be a good fit for us. Thanks @waciumawanjohi

**Comment by waciumawanjohi** [comment]
Hi @angle943 
Last we talked you were planning to evaluate these LaTeX courses and making a recommendation of one. Have you been able to do so?

**Comment by andrew-werdna** [comment]
Just adding my support for LaTeX courses!

**Comment by speightashley** [comment]
I've gone through this video on youtube to get a basic understanding of it: https://www.youtube.com/watch?v=ydOTMQC7np0&t=3838s

Adding a course section would be good though because it's almost impossible to keep notes from lecture videos without knowing Latex unless you are taking notes with pen and paper.

**Comment by owenekblad** [comment]
As a working mathematician, I have never taken a proper LaTeX course, meaning, I don't know how to do much more than write up a document that looks pretty using a random template that I have refined over the years. Typically in an introduction to proofs course, you will be taught 'LaTeX', in the sense that your homeworks will be given to you as a shared file in Overleaf, and you will be encouraged (but not required) to submit homework in Overleaf. 

Overleaf itself has a great deal of resources for learning the very basics of LaTeX, which is all I have ever really needed, besides the occasional Google search to suit my needs. A more technical exposition of LaTeX is, in my opinion, superfluous to an education in pure mathematics. LaTeX at the undergraduate level should be a useful tool in teaching the student to write organized and good-looking mathematics. Anything beyond this is, in my opinion, too specialized.

**Comment by waciumawanjohi** [comment]
In the comment period (2 years!) we've had exactly one recommendation. So that's going to be the recommended course. [Overleaf's "Learn LaTeX in 30 minutes"](https://www.overleaf.com/learn/latex/Learn_LaTeX_in_30_minutes).
