### ISSUE TITLE
The course "Introduction to Differential Equations"

### ISSUE THREAD

**Issue by Diushen** [ossu/math#36]
I tried to enter the course but EdX says "We can't seem to find the page you're looking for.", so I don't know if it is not available anymore.

**Comment by zzzxxx729** [comment]
Yeah, I think that, and every "Differential Equations" courses have the same issue.

**Comment by waciumawanjohi** [comment]
Thanks for raising the issue. The link for Intro to Diff Eq has been updated. Some of the later Diff EQ courses are still unavailable and will need further work. Suggestions welcome!
