### ISSUE TITLE
MATLAB

### ISSUE THREAD

**Issue by Chardelyce** [ossu/math#38]
Can we add matlab training courses as it is synonymous with statistics, graphing, solving complex equations and is just something nice to learn :) ?

**Comment by waciumawanjohi** [comment]
This suggestion is similar to #29. As in that issue there are a couple of steps that need to occur:
1. Justify the need. "it is synonymous with statistics, graphing, solving complex equations" Can you back up this claim? It is not self evident. "is just something nice to learn :)" That's definitely not enough to add a course to the curriculum. OSSU remains useful only if it avoids recommending too much to students.
2. Identify course options. This is generally a few hours work, looking at sources like class central, relevant reddit communities and then doing web searches to ID the courses on offer.
3. Evaluate the offerings. This is _many_ hours of work. It involves taking notes that compare the syllabi, resources (lectures, texts, assignments, assessments), community and more for each course. Once completed, those notes need to be synthesized for others to understand.

Recommendations that go through this process will be added to the curriculum!
