### ISSUE TITLE
What do we do for the advanced section without courses?

### ISSUE THREAD

**Issue by speightashley** [ossu/math#44]
Is this project still being maintained?

I saw that the most recent updates didn't change much and the courses haven't been updated in a while.

I spent some time last night going through the MIT Opencourseware looking at courses that fit into the syllabus for the advanced section and it seems that there are good selection of courses that would tick the boxes. Granted, not all of them come with video lectures but there is a still decent selection that come with lecture notes etc. 

Has anyone taken a look through the other published university courses that could be used?

**Comment by waciumawanjohi** [comment]
This comment in the issue immediately preceding this one may be of help: https://github.com/ossu/math/issues/42#issuecomment-2093662545

If you have a suggestion for additions to the curriculum, I encourage you to open an RFC for each addition. The contribution guide from the computer science curriculum may be of use: https://github.com/ossu/computer-science/blob/master/CONTRIBUTING.md
